version: '3.7'
services:
    nginx:
        image: nginx
        container_name: elk-nginx
        ports:
            - 80:80
            - 443:443
        networks:
            - internal-network
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
        restart: unless-stopped
    elk:
        image: sebp/elk
        container_name: elk
        ports:
            - 9200:9200
            - 5044:5044
        expose:
            - 5601
        networks:
            - internal-network
        volumes:
            - ./data:/var/lib/elasticsearch
        depends_on:
            - nginx
        restart: unless-stopped

networks:
    internal-network:
        external: true
        