version: '3.7'
services:
  skywalking-server:
    image: apache/skywalking-oap-server:7.0.0-es6
    container_name: skywalking-server
    restart: unless-stopped
    tty: true
    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"
    networks:
      - internal-network
  skywalking-ui:
    image: apache/skywalking-ui
    container_name: skywalking-ui
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: skywalking-server:12800
    networks:
      - internal-network
            
networks:
  internal-network:
    external: true
