version: '3.7'
services:
    mattermost:
        image: mattermost/mattermost-preview
        container_name: mattermost
        restart: unless-stopped
        tty: true
        ports:
            - "8065:8065"
        extra_hosts:
            dockerhost: 127.0.0.1