version: '3.7'
services:
    mysql:
        image: postgres:12
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data:/var/lib/postgresql
        networks:
            - internal-network
            
networks:
    internal-network:
        external: true
