version: '3.7'
services:
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - D:\~temp\docker-compose\redis\data:/data
        networks:
            - internal-network

networks:
    internal-network:
        external: true